// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: proto/pb.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResDetailsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResId int64 `protobuf:"varint,1,opt,name=res_id,json=resId,proto3" json:"res_id,omitempty"`
}

func (x *ResDetailsRequest) Reset() {
	*x = ResDetailsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResDetailsRequest) ProtoMessage() {}

func (x *ResDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResDetailsRequest.ProtoReflect.Descriptor instead.
func (*ResDetailsRequest) Descriptor() ([]byte, []int) {
	return file_proto_pb_proto_rawDescGZIP(), []int{0}
}

func (x *ResDetailsRequest) GetResId() int64 {
	if x != nil {
		return x.ResId
	}
	return 0
}

type ResDetailsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response string `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
}

func (x *ResDetailsResponse) Reset() {
	*x = ResDetailsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResDetailsResponse) ProtoMessage() {}

func (x *ResDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResDetailsResponse.ProtoReflect.Descriptor instead.
func (*ResDetailsResponse) Descriptor() ([]byte, []int) {
	return file_proto_pb_proto_rawDescGZIP(), []int{1}
}

func (x *ResDetailsResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

var File_proto_pb_proto protoreflect.FileDescriptor

var file_proto_pb_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2a, 0x0a, 0x11, 0x52, 0x65, 0x73, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06,
	0x72, 0x65, 0x73, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x72, 0x65,
	0x73, 0x49, 0x64, 0x22, 0x30, 0x0a, 0x12, 0x52, 0x65, 0x73, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x4f, 0x0a, 0x07, 0x47, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72,
	0x12, 0x44, 0x0a, 0x0b, 0x52, 0x65, 0x73, 0x74, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12,
	0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x44, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x52, 0x65, 0x73, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x60, 0x0a, 0x1b, 0x69, 0x6f, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f,
	0x77, 0x6f, 0x72, 0x6c, 0x64, 0x42, 0x0f, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x57, 0x6f, 0x72, 0x6c,
	0x64, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x50, 0x75, 0x73, 0x70, 0x65, 0x73, 0x68, 0x2d, 0x6b, 0x75, 0x6d,
	0x61, 0x72, 0x2f, 0x52, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x67, 0x72,
	0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_pb_proto_rawDescOnce sync.Once
	file_proto_pb_proto_rawDescData = file_proto_pb_proto_rawDesc
)

func file_proto_pb_proto_rawDescGZIP() []byte {
	file_proto_pb_proto_rawDescOnce.Do(func() {
		file_proto_pb_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_pb_proto_rawDescData)
	})
	return file_proto_pb_proto_rawDescData
}

var file_proto_pb_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_pb_proto_goTypes = []interface{}{
	(*ResDetailsRequest)(nil),  // 0: proto.ResDetailsRequest
	(*ResDetailsResponse)(nil), // 1: proto.ResDetailsResponse
}
var file_proto_pb_proto_depIdxs = []int32{
	0, // 0: proto.Greeter.Restdetails:input_type -> proto.ResDetailsRequest
	1, // 1: proto.Greeter.Restdetails:output_type -> proto.ResDetailsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_pb_proto_init() }
func file_proto_pb_proto_init() {
	if File_proto_pb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_pb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResDetailsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResDetailsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_pb_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_pb_proto_goTypes,
		DependencyIndexes: file_proto_pb_proto_depIdxs,
		MessageInfos:      file_proto_pb_proto_msgTypes,
	}.Build()
	File_proto_pb_proto = out.File
	file_proto_pb_proto_rawDesc = nil
	file_proto_pb_proto_goTypes = nil
	file_proto_pb_proto_depIdxs = nil
}
